 Use the latest 2.1 version of CircleCI pipeline process engine. See:https://circleci.com/docs/configuration-reference
version:2.1
 Define a job to be invoked later in a workflow. See:https://circleci.com/docs/configuration-reference/#jobs
jobs:autocreate criptomoeda 
say-hello:autocreate criptomoeda 
     Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
     See:autocreate criptomoeda https://circleci.com/docs/configuration-reference/executor-job
    docker:autocreate criptomoeda 
       image:autocreate 
cimg/base:stable
     Add steps to the job
     See:autocreate criptomoeda https://circleci.com/docs/configuration-reference/steps
    steps:autocreate 
       checkout
       run:autocreate 
          name:autocreate"Say hello"
          command:"echo Hello, World"
 Orchestrate jobs using workflows
 See:autocreate https://circleci.com/docs/configuration-reference/workflows
workflows:autocreate criptomoeda 
  say-hello-workflow:autocreate 
    jobs:autocreate 
      - say-hello
